import { numMatchingSubseq } from "./number-of-matching-subsequences";

test.each`
    s               | words                                            | expectedOutput
    ${"abcde"}      | ${["a", "bb", "acd", "ace"]}                     | ${3}
    ${"dsahjpjauf"} | ${["ahjpjau", "ja", "ahbwzgqnuk", "tnmlanowax"]} | ${2}
`("_($s, $words) -> $expectedOutput", ({ s, words, expectedOutput }: any) => {
    let result = numMatchingSubseq(s, words);
    expect(result).toBe(expectedOutput);
});

test("time limit", () => {
    let s =
        "ricogwqznwxxcpueelcobbbkuvxxrvgyehsudccpsnuxpcqobtvwkuvsubiidjtccoqvuahijyefbpqhbejuisksutsowhufsygtwteiqyligsnbqglqblhpdzzeurtdohdcbjvzgjwylmmoiundjscnlhbrhookmioxqighkxfugpeekgtdofwzemelpyjsdeeppapjoliqlhbrbghqjezzaxuwyrbczodtrhsvnaxhcjiyiphbglyolnswlvtlbmkrsurrcsgdzutwgjofowhryrubnxkahocqjzwwagqidjhwbunvlchojtbvnzdzqpvrazfcxtvhkruvuturdicnucvndigovkzrqiyastqpmfmuouycodvsyjajekhvyjyrydhxkdhffyytldcdlxqbaszbuxsacqwqnhrewhagldzhryzdmmrwnxhaqfezeeabuacyswollycgiowuuudrgzmwnxaezuqlsfvchjfloczlwbefksxsbanrektvibbwxnokzkhndmdhweyeycamjeplecewpnpbshhidnzwopdjuwbecarkgapyjfgmanuavzrxricbgagblomyseyvoeurekqjyljosvbneofjzxtaizjypbcxnbfeibrfjwyjqrisuybfxpvqywqjdlyznmojdhbeomyjqptltpugzceyzenflfnhrptuugyfsghluythksqhmxlmggtcbdddeoincygycdpehteiugqbptyqbvokpwovbnplshnzafunqglnpjvwddvdlmjjyzmwwxzjckmaptilrbfpjxiarmwalhbdjiwbaknvcqovwcqiekzfskpbhgxpyomekqvzpqyirelpadooxjhsyxjkfqavbaoqqvvknqryhotjritrkvdveyapjfsfzenfpuazdrfdofhudqbfnzxnvpluwicurrtshyvevkriudayyysepzqfgqwhgobwyhxltligahroyshfndydvffd";
    let words = [
        "iowuuudrgzmw",
        "azfcxtvhkruvuturdicnucvndigovkzrq",
        "ylmmo",
        "maptilrbfpjxiarmwalhbd",
        "oqvuahijyefbpqhbejuisksutsowhufsygtwteiqyligsnbqgl",
        "ytldcdlxqbaszbuxsacqwqnhrewhagldzhr",
        "zeeab",
        "cqie",
        "pvrazfcxtvhkruvuturdicnucvndigovkzrqiya",
        "zxnvpluwicurrtshyvevkriudayyysepzq",
        "wyhxltligahroyshfn",
        "nhrewhagldzhryzdmmrwn",
        "yqbvokpwovbnplshnzafunqglnpjvwddvdlmjjyzmw",
        "nhrptuugyfsghluythksqhmxlmggtcbdd",
        "yligsnbqglqblhpdzzeurtdohdcbjvzgjwylmmoiundjsc",
        "zdrfdofhudqbfnzxnvpluwicurrtshyvevkriudayyysepzq",
        "ncygycdpehteiugqbptyqbvokpwovbnplshnzafun",
        "gdzutwgjofowhryrubnxkahocqjzww",
        "eppapjoliqlhbrbgh",
        "qwhgobwyhxltligahroys",
        "dzutwgjofowhryrubnxkah",
        "rydhxkdhffyytldcdlxqbaszbuxs",
        "tyqbvokpwovbnplshnzafunqglnpjvwddvdlmjjyzmwwxzjc",
        "khvyjyrydhxkdhffyytldcdlxqbasz",
        "jajekhvyjyrydhxkdhffyytldcdlxqbaszbuxsacqwqn",
        "ppapjoliqlhbrbghq",
        "zmwwxzjckmaptilrbfpjxiarm",
        "nxkahocqjzwwagqidjhwbunvlchoj",
        "ybfxpvqywqjdlyznmojdhbeomyjqptltp",
        "udrgzmwnxae",
        "nqglnpjvwddvdlmjjyzmww",
        "swlvtlbmkrsurrcsgdzutwgjofowhryrubn",
        "hudqbfnzxnvpluwicurr",
        "xaezuqlsfvchjf",
        "tvibbwxnokzkhndmdhweyeycamjeplec",
        "olnswlvtlbmkrsurrcsgdzu",
        "qiyastqpmfmuouycodvsyjajekhvyjyrydhxkdhffyyt",
        "eiqyligsnbqglqblhpdzzeurtdohdcbjvzgjwyl",
        "cgiowuuudrgzmwnxaezuqlsfvchjflocz",
        "rxric",
        "cygycdpehteiugqbptyqbvokpwovbnplshnzaf",
        "g",
        "surrcsgd",
        "yzenflfnhrptuugyfsghluythksqh",
        "gdzutwgjofowhryrubnxkahocqjzwwagqid",
        "ddeoincygycdpeh",
        "yznmojdhbeomyjqptltpugzceyzenflfnhrptuug",
        "ejuisks",
        "teiqyligsnbqglqblhpdzzeurtdohdcbjvzgjwylmmoi",
        "mrwnxhaqfezeeabuacyswollycgio",
        "qfskkpfakjretogrokmxemjjbvgmmqrfdxlkfvycwalbdeumav",
        "wjgjhlrpvhqozvvkifhftnfqcfjmmzhtxsoqbeduqmnpvimagq",
        "ibxhtobuolmllbasaxlanjgalgmbjuxmqpadllryaobcucdeqc",
        "ydlddogzvzttizzzjohfsenatvbpngarutztgdqczkzoenbxzv",
        "rmsakibpprdrttycxglfgtjlifznnnlkgjqseguijfctrcahbb",
        "pqquuarnoybphojyoyizhuyjfgwdlzcmkdbdqzatgmabhnpuyh",
        "akposmzwykwrenlcrqwrrvsfqxzohrramdajwzlseguupjfzvd",
        "vyldyqpvmnoemzeyxslcoysqfpvvotenkmehqvopynllvwhxzr",
        "ysyskgrbolixwmffygycvgewxqnxvjsfefpmxrtsqsvpowoctw",
        "oqjgumitldivceezxgoiwjgozfqcnkergctffspdxdbnmvjago",
        "bpfgqhlkvevfazcmpdqakonkudniuobhqzypqlyocjdngltywn",
        "ttucplgotbiceepzfxdebvluioeeitzmesmoxliuwqsftfmvlg",
        "xhkklcwblyjmdyhfscmeffmmerxdioseybombzxjatkkltrvzq",
        "qkvvbrgbzzfhzizulssaxupyqwniqradvkjivedckjrinrlxgi",
        "itjudnlqncbspswkbcwldkwujlshwsgziontsobirsvskmjbrq",
        "nmfgxfeqgqefxqivxtdrxeelsucufkhivijmzgioxioosmdpwx",
        "ihygxkykuczvyokuveuchermxceexajilpkcxjjnwmdbwnxccl",
        "etvcfbmadfxlprevjjnojxwonnnwjnamgrfwohgyhievupsdqd",
        "ngskodiaxeswtqvjaqyulpedaqcchcuktfjlzyvddfeblnczmh",
        "vnmntdvhaxqltluzwwwwrbpqwahebgtmhivtkadczpzabgcjzx",
        "yjqqdvoxxxjbrccoaqqspqlsnxcnderaewsaqpkigtiqoqopth",
        "wdytqvztzbdzffllbxexxughdvetajclynypnzaokqizfxqrjl",
        "yvvwkphuzosvvntckxkmvuflrubigexkivyzzaimkxvqitpixo",
        "lkdgtxmbgsenzmrlccmsunaezbausnsszryztfhjtezssttmsr",
        "idyybesughzyzfdiibylnkkdeatqjjqqjbertrcactapbcarzb",
        "ujiajnirancrfdvrfardygbcnzkqsvujkhcegdfibtcuxzbpds",
        "jjtkmalhmrknaasskjnixzwjgvusbozslrribgazdhaylaxobj",
        "nizuzttgartfxiwcsqchizlxvvnebqdtkmghtcyzjmgyzszwgi",
        "egtvislckyltpfogtvfbtxbsssuwvjcduxjnjuvnqyiykvmrxl",
        "ozvzwalcvaobxbicbwjrububyxlmfcokdxcrkvuehbnokkzala",
        "azhukctuheiwghkalboxfnuofwopsrutamthzyzlzkrlsefwcz",
        "yhvjjzsxlescylsnvmcxzcrrzgfhbsdsvdfcykwifzjcjjbmmu",
        "tspdebnuhrgnmhhuplbzvpkkhfpeilbwkkbgfjiuwrdmkftphk",
        "jvnbeqzaxecwxspuxhrngmvnkvulmgobvsnqyxdplrnnwfhfqq",
        "bcbkgwpfmmqwmzjgmflichzhrjdjxbcescfijfztpxpxvbzjch",
        "bdrkibtxygyicjcfnzigghdekmgoybvfwshxqnjlctcdkiunob",
        "koctqrqvfftflwsvssnokdotgtxalgegscyeotcrvyywmzescq",
        "boigqjvosgxpsnklxdjaxtrhqlyvanuvnpldmoknmzugnubfoa",
        "jjtxbxyazxldpnbxzgslgguvgyevyliywihuqottxuyowrwfar",
        "zqsacrwcysmkfbpzxoaszgqqsvqglnblmxhxtjqmnectaxntvb",
        "izcakfitdhgujdborjuhtwubqcoppsgkqtqoqyswjfldsbfcct",
        "rroiqffqzenlerchkvmjsbmoybisjafcdzgeppyhojoggdlpzq",
        "xwjqfobmmqomhczwufwlesolvmbtvpdxejzslxrvnijhvevxmc",
        "ccrubahioyaxuwzloyhqyluwoknxnydbedenrccljoydfxwaxy",
        "jjoeiuncnvixvhhynaxbkmlurwxcpukredieqlilgkupminjaj",
        "pdbsbjnrqzrbmewmdkqqhcpzielskcazuliiatmvhcaksrusae",
        "nizbnxpqbzsihakkadsbtgxovyuebgtzvrvbowxllkzevktkuu",
        "hklskdbopqjwdrefpgoxaoxzevpdaiubejuaxxbrhzbamdznrr",
        "uccnuegvmkqtagudujuildlwefbyoywypakjrhiibrxdmsspjl",
        "awinuyoppufjxgqvcddleqdhbkmolxqyvsqprnwcoehpturicf",
    ];
    let result = numMatchingSubseq(s, words);
    expect(result).toBe(51);
});
