"""Wrapper for testing with jest
"""

load("@npm//jest:index.bzl", _jest_test = "jest_test")

def jest_test(name, srcs, **kwargs):
    """A macro around the autogenerated jest test rule

    Args:
        name: name
        srcs: srcs
        **kwargs: **kwargs
    """
    args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
    ]
    for src in srcs:
        args.extend(["--runTestsByPath", "$(location %s)" % src])

    data = ["@npm//@types/jest", "@npm//tslib", "@npm//ts-jest"]
    data.extend(srcs)
    data.extend(["//tools:list-node.ts", "//tools:tree-node.ts"])
    data.extend(["//:jest.config.json", "//:tsconfig.json"])

    _jest_test(
        name = name,
        data = data,
        args = args,
        **kwargs
    )
